### ISSUE TITLE
Add resolution auto-detection on startup

### ISSUE THREAD

**Issue by NickZ** [drfrag666/gzdoom#12]
Thank you for this! We have chosen LZDoom to be the source port bundled with the official snap package of Freedoom, because I wanted a modern source port that was more flexible than GZDoom in terms of the hardware it could run on, including the raspi. 

One thing that I noticed in packaging this: in recent versions, GZDoom has the option to automatically detect the desktop resolution and set it upon startup. Currently, what I'm doing in the package right now is just setting full screen and 848x480 as the resolution, since I know that is something that will work on most systems and provides a decent "out-of-the-box" experience. It would be nice for LZDoom to automatically detect the resolution so that I don't have to set this.

**Comment by drfrag666** [comment]
Thanks! Sorry i can't do that, LZDoom right now uses the ancient ZDoom code and some people prefer that. GZDoom uses a borderless window now and on some machines it can be slow due to problems with DWM. But i can say this will unavoidably change in the future.
