### ISSUE TITLE
Add "Scale to nearest integer" for status bar

### ISSUE THREAD

**Issue by NickZ** [drfrag666/gzdoom#14]
Right now, the status bar is set by default to "Scale to fullscreen"; however, if the resolution is set to something other than a multiple of 640x400, it will not scale linearly and it will look somewhat distorted, especially on lower resolutions. Using the "use default scale" option will cause the HUD to scale linearly, but will cause the status bar to be very small on higher resolutions. We can choose the integer scale for the status bar ourselves, but the optimal setting differs between default resolutions.

A good option between all these would be to add an option to automatically scale to the nearest integer for the status bar, so that it fills the screen but also isn't distorted

**Comment by drfrag666** [comment]
Sorry i can't do that, dpJudas implemented the scaling options. Is even possible to have integer scaling and an arbitrary resolution? I don't think so.
