### ISSUE TITLE
Please make a DOS version of ZDoom32 or like this (DJGPP)

### ISSUE THREAD

**Issue by DartPower** [drfrag666/gzdoom#3]
Please make a DOS version of ZDoom32 or like this (DJGPP)

Last ZDoom in DOS version is 1.17c
http://prdownloads.sourceforge.net/zdoom/zdoom-1.17c.zip

And this is a source of this.
http://prdownloads.sourceforge.net/zdoom/zdoom-1.17c-src.zip

This is a will be an good experiment :)

**Comment by drfrag666** [comment]
Sorry but that's technically impossible and moreover it wouldn't make much sense. Even porting the GL version of ZDoom LE would require some serious work.
