### ISSUE TITLE
Keeping up the Win98 compatibility

### ISSUE THREAD

**Issue by mallory98e** [drfrag666/gzdoom#36]
First of all thanks for this great engine, I found it after giving up on zdoom/gzdoom and whatever else was not working on 9x.

https://www.doomworld.com/forum/topic/93413-zdoom-le-legacy-edition/

Is the  ZDoom LE 2.8.2a (GL 1.8.4b) APR 10 2018 the last version for Win98 SE?

Are you planning to keep developing it for 9X? It would be very nice it's literally the best retro gaming OS, runs a variety of DOS games and games up to the morrowind/half life era.

**Comment by Wohlstand** [comment]
There is not just Windows 98's API: the recent version of GZDoom focuses on using modern OpenGL and Vulkan support, and, obviously, these APIs aren't supported by 9x at all.

**Comment by Wohlstand** [comment]
P.S. I know Windows 98 by myself since childhood, and I know that its the best to run old games, especially these are work on Windows XP glitchy or doesn't work at all. And so, sometimes I run Windows 98 on old hardware or on emulator to run various stuff on it.

**Comment by drfrag666** [comment]
No, the last version of LE is 2.8.3a.
https://github.com/drfrag666/gzdoom/releases/tag/2.8.3a

Besides ZDoom32 also runs on 98 but without the GL renderer.
https://github.com/drfrag666/zdoom32/releases/tag/2.8.6a

Finally ZZDoom runs on Vista and later but can be compiled for XP.

I know 98 very well, i don't think it's really useful for anything besides running DOS and Win3.x games. Win95 games run well on XP SP1, i think you'll need ACT 3 (compatibility toolkit) for some of them. 98 is very limited and runs best on pentium class hardware but for anything later XP is fine with some extra ram.
