### ISSUE TITLE
LZDoom 3.88b crash with 32bit version in Ashes Afterglow

### ISSUE THREAD

**Issue by pachuco** [drfrag666/gzdoom#37]
When level-change to Badlands(Prosperity town level) from either Nuke Plant or from Water Treatment sewer, game crashes.
This crash only occurs with 32 bit build, and works fine on 64 bit one. Tested 32bit build on x86 winXP and x64 win7 machines, so crash is repeatable.

Attached are two saves near exit to Badlands. One for sewer and one for nuke plant.
[savemeeeeeeeee.zip](https://github.com/drfrag666/gzdoom/files/10227634/savemeeeeeeeee.zip)

Oh yeah, mod is AshesAfterglow1_10.pk3 with MD5 of 9EDD04EF0E9445563566C98B2E3653C1
https://forum.zdoom.org/viewtopic.php?t=69612

**Comment by drfrag666** [comment]
Sorry but i discontinued the port. That said the last version working on XP is 3.87c with a fix. Some mods could not load with the version compiled using the VS XP toolset.

**Comment by pachuco** [comment]
My two cents worth of guessing without looking at any code say: integer overflow where integer width of variable changes with platform-compiled-for bitness.

**Comment by drfrag666** [comment]
It crashes with the 64 bit build too, but seems it's random. For me it has crashed once only with the first savegame.
The mod is rather big about 250 MB.
The port compiled with MinGW-w64 not long ago and still should, i left instructions in the wiki. But that compiler didn't work very well i recommend using VS 2019.
BTW are you from Spain by any chance? Your nick sounds like that.

**Comment by pachuco** [comment]
> BTW are you from Spain by any chance? Your nick sounds like that.

Nah. The nick is holdover from Mibbit.
