### ISSUE TITLE
Sprite transparent bug in software ,Truecolor Polyobject with Direct x. And linear upscaling y midmapping don´t working in truepoly

### ISSUE THREAD

**Issue by hyperJJmaster** [drfrag666/gzdoom#5]
![screenshot_doom_20181219_201851](https://user-images.githubusercontent.com/24927155/50259560-9176ac80-03d2-11e9-95ff-2be86463afc5.png)

**Comment by hyperJJmaster** [comment]
Without polyrender 
![screenshot_doom_20181219_212901](https://user-images.githubusercontent.com/24927155/50260163-2c708600-03d5-11e9-9717-795c6efde539.png)

With polyrender
![Uploading Screenshot_Doom_20181219_212909.png…]()

**Comment by drfrag666** [comment]
I've suffered an accident and won't be able to look into this at least for now.
 Was GZDoom 3.3.2 affected? What about earlier betas?
 And post a runnable sample.

**Comment by drfrag666** [comment]
Now that i think of it mipmapping was never implemented in softpoly. This is a GZDoom clone so if it's not in GZDoom same here. I'm closing this.
