### ISSUE TITLE
Missing cmdlib.h include in src/posix/i_steam.cpp

### ISSUE THREAD

**Issue by OrdinaryMagician** [drfrag666/gzdoom#6]
Won't build on Linux without this.

**Comment by drfrag666** [comment]
I just saw your message yesterday. Really? The include is there, which error do you get?

**Comment by OrdinaryMagician** [comment]
You can close this if this no longer applies. :P

**Comment by OrdinaryMagician** [comment]
Reopening because I just realized that it's still happening.
```
src/posix/i_steam.cpp:208:7: error: ‘FileExists’ was not declared in this scope
   if(!FileExists(regPath))
       ^~~~~~~~~~
```
This is specifically in the default branch.

**Comment by drfrag666** [comment]
I see you're compiling ZDoom32, i forgot it was still the default branch. Please try now, it should compile. Same problem with ZDoom LE.

**Comment by OrdinaryMagician** [comment]
Ah, after this I'm seeing theres also an issue with oalsound.cpp. It appears that including <functional> is needed for std::mem_fn.

**Comment by drfrag666** [comment]
Fixed, should compile now. But that code is very old and the include was added much later. I'd swear it compiled for me.

**Comment by OrdinaryMagician** [comment]
Well, that's it then.

**Comment by drfrag666** [comment]
Never mind, i hooked the Travis-CI service.
