### ISSUE TITLE
src/p_spec.cpp hexenScrollies array triggers multiple gcc errors

### ISSUE THREAD

**Issue by OrdinaryMagician** [drfrag666/gzdoom#7]
Seeing various `narrowing conversion from int to char` errors in that array. Could just be worked around by adding -Wno-narrowing to the compiler flags in cmake. They array could also be made of ints and I doubt there'd be much consequence for this other than taking up 4 times the memory (which is relatively unnoticeable).

**Comment by drfrag666** [comment]
You mean warnings right? I think those have been there almost since ever.

**Comment by OrdinaryMagician** [comment]
Dunno why but those specific warnings were treated as errors. I don't even know if this triggers anymore.
