### ISSUE TITLE
Textures don't scale in software renderer in all GZDoom Legacy releases (including 3.8.1)

### ISSUE THREAD

**Issue by mjr4077au** [drfrag666/gzdoom#9]
When running in the software renderer, enabling scaling under Texture Options scales the fonts and sprites, but not textures.

Testing [GZDoom 3.7.0](https://forum.zdoom.org/viewtopic.php?t=63032) the first release where this feature was introduced, it works as expected. Testing the legacy release on that page, and the latest one, it does not.

If this could be looked at and fixed, I'd be appreciative :)

**Comment by drfrag666** [comment]
Do you mean the HQ resize modes right? They never worked in software at all, the vintage build is based on a master previous to 3.4. That feature requires the new texture manager, same as extended localization so both are out.
 It's not a bug, just i could not merge it. Those options are in the GL section for a reason.
